### ISSUE TITLE
A few icons missing

### ISSUE THREAD

**Issue by glennpc** [B00ze64/FF-Menu-Icon-Plus-CSS#1]
First off, thank you for making this available. It looks great on my FF 79 running Windows 10. I'm using your default theme Fugue Plus. I have noticed a few icons missing on the context menu when you click over a blank area of a page.  Back, Forward, Reload and Bookmark This Page are the ones missing. I'll attach a screen capture of it below. I have icons showing everywhere else.
![FF-MenuIconPlusCSS](https://user-images.githubusercontent.com/54756104/90180218-80c33900-dd63-11ea-8858-ee4b26796e31.png)

**Comment by glennpc** [comment]
I just found out why those icons were missing. I had enable context_bfrsb_labels_with_icons.css in the userChrome.css file. Now everything is showing up.
![fixed](https://user-images.githubusercontent.com/54756104/90187654-f97bc280-dd6e-11ea-9c87-e19a72d19385.png)

**Comment by B00ze64** [comment]
Good day @glennpc.

You are using one of Aris-t2's CSS, to show the Back/Forward as a menu label, because normally it looks like this, with no labels, they are there (otherwise Aris would not be able to show them) but they are hidden:

![image](https://user-images.githubusercontent.com/15389810/90206258-bfdca300-ddd2-11ea-9473-90576c729dc7.png)

Glad you found a solution, less work for me lol.

But you made me discover I forgot to add icons to Save-Page-WE context menu - so Back to work for me!

Thanks.
