### ISSUE TITLE
Bookmarks Menu overlapped icon (Fugue Plus) Fx 78.1

### ISSUE THREAD

**Issue by docrR** [B00ze64/FF-Menu-Icon-Plus-CSS#2]
Using your script in conjunction with Aris's CustomCSSforFx. First off, props to your incredible work. I don't even remember the original Menu Icons Plus extension being this comprehensive.

I've noticed a few minor snags with the Bookmarks menu, however. Both the the filemenu and "panel". 
To start, the filemenu. As shown in the image, there's an overlap on the 'Mobile Bookmarks' entry where the cellphone and folder submenu icon seem to be competing for the entry.
![bug](https://user-images.githubusercontent.com/68521531/90322077-d3e0eb80-df1d-11ea-9e4b-f2997b1c54ef.png)

The other issue is in the panel, which I realize isn't (yet) the focus of this project. 
![bug 2](https://user-images.githubusercontent.com/68521531/90322136-6b463e80-df1e-11ea-92af-be0a511970f3.png)
The green + icon resource is overlapping the panel text in this case. 

My settings are relatively vanilla, I just enabled the entries in your script to show a few classic Ff icons where possible.

Furthermore, I do have one question. When do you do begin skinning the panel menus (Hamburger, etc), would it be possible to  style address/search icons or the Site Information dialogue?

Thanks

**Comment by B00ze64** [comment]
Hi @docrR,

Wow, you've managed to make the Mobile Bookmarks menu appear! I thought it was just left behind and no longer used, I could not get it to appear by just adding another browser to sync with. I see it needs a list-style-image rather than an insert of an element, and it gets styled by .bookmark-item[container] in Aris's CSS. Wish I could make this appear without needing to setup my Android to sync with Firefox, guess I'll have to.

For the Open All In Tabs in the BMB, I had no intention to add an icon there lol, but my adding one to the bookmarks menu items (the menu in the titlebar) is adding one to BMB as well. I'll see what I can do, I can reproduce here.

The old Menu Icon Plus extension was *trying* to add all those icons I've added. I've changed icons and moved things around some, but the extension had most of what you see now, it's just that it wasn't working right for some reason. I have a screenshot I took before I upgraded to V77 (and discovered it had no icons whatsoever) and it is missing a lot of stuff that *was* in the MIP extension. Dunno why it wasn't working right.

Thanks for reporting.
Later,

**Comment by docrR** [comment]
Interesting. I wasn't actually aware the Mobile Bookmarks entry was non-present on new profiles, but I suppose it's from my (brief) times syncing on Firefox Fennic. My primary Android browser rn is Bromite tho.

Well thanks for taking a look into it. Again can't get over this script, it's truly amazing. I'll be showing it to others in the hopes of increasing awareness. Seeing those white 'panels' skinned in the future would be a dream too, lol. Only a matter of time before they take over the native contextual menus. 

I see. I remember a lot of extensions started behaving oddly with Australis, (v29 - 56 iirc?) Menu Icons Plus being no exception. Or themes requiring more prerequisites to look as intended. Some supporting the use of CTR, others imploding with it enabled.  Perhaps I'm among the vocal minority for actually preferring Photon... Just less so keen on the fact that userChrome and js mods are housed on Github instead of AMO with lowlevel webextensions, needing to be manually injected into profile. Can't have everything 0.o hehehe

**Comment by B00ze64** [comment]
Hi @docrR.

The Mobile Bookmarks menu is **there** but it's invisible, I guess until you sync a mobile. I signed-in Firefox from my cellphone tonight, but the darn thing refuses to sync. This being mobile Firefox, I do not have access to the browser console, so I have no idea why it won't sync.

I've hopefully fixed the Mobile Bookmarks entry, and I made a folder image specifically for that menu for the fugue Themes. Can you download the mip_FuguePlus-Menus CSS file and the MipImages/Fugue/MobileBookmarksFolder.png image and try it? If that works, all the other themes will also work.

As far as Open All In Tabs, I've fixed that too. I also added code to add the icon to the panel properly, but that's for the upcoming panels files, not released yet (barely started.) So the TAB+ image is just not applied to the panel for now.

`Well thanks for taking a look into it. Again can't get over this script, it's truly amazing. I'll be showing it to others in the hopes of increasing awareness. Seeing those white 'panels' skinned in the future would be a dream too, lol. Only a matter of time before they take over the native contextual menus.`

Thanks, I have not really worked on awareness yet lol, your help is appreciated. And yes, it is only a matter of time before it ALL becomes "Panels" instead of XUL menus. For now they are mostly in the hamburger menu and we can use Aris's CSS to add black SVG icons to some of the entries, so it does not look too empty. The BMB (Bookmarks Panel) is skinned by the *colorized* CSS from Aris and I already modify that according to the theme, so that one's mostly done :-)

`Perhaps I'm among the vocal minority for actually preferring Photon... Just less so keen on the fact that userChrome and js mods are housed on Github instead of AMO with lowlevel webextensions, needing to be manually injected into profile. `

I'm already used to the way it looks now, but when I upgraded from FF52 to FF77 I wanted my curvy tabs back lol. There's CSS for that out there, but it does not work perfectly. And anyway, the new FF works with Windows 10, it adjusts to the Windows colors, which is okay. And yeah, having to manually use CSS instead of an extension is kind of a pain...

Thank you.
Best Regards,

**Comment by docrR** [comment]
That did it. Thanks

![image](https://user-images.githubusercontent.com/68521531/90540007-94e5ac80-e14e-11ea-9281-91c7c38cb249.png)
![image](https://user-images.githubusercontent.com/68521531/90540062-a6c74f80-e14e-11ea-855f-5298fce72436.png)
![image](https://user-images.githubusercontent.com/68521531/90540164-cd858600-e14e-11ea-80f1-690e953e9c1e.png)

**Comment by B00ze64** [comment]
Thanks, I'll make a new zip. 

Are you using the classic Firefox icons on top of Fugue? That "View Bookmarks Sidebar" should be a blue book, and "Show All Bookmarks" should be an opened blue book...?

And I see the Mobile Bookmarks item in the BMB is not using my new image either. I'll fix that, nice of you to show me :-)

Regards,

**Comment by docrR** [comment]
Hi there again.

Yes indeed, I'm using the Classic Firefox icons overrides. It fits my Firefox 3.6-looking arrangement via Aris's CSS.

And yes I noticed the generic BMB item as well. Fortunately it's not glitchy looking, at least.

For ref, this is what I've conjured up using Aris's CSS/js + your project. I have another variant too where all the frame above the bookmarks bar is translucent like IE7/8:

![image](https://user-images.githubusercontent.com/68521531/90583693-c8e8be00-e19e-11ea-81ee-1421c6345ad5.png)

Cordially

**Comment by B00ze64** [comment]
Wow, that looks good! Hmmm, "Bookmark This Page" should be a pale Star, I forgot to override that, but since I did not have Back/Forward/Refresh icons I did not override "Bookmark this page" either. I'll see what I can find for those 4 in FF24/FF52, maybe I can find something to use. Best Regards,

**Comment by docrR** [comment]
Yeah, I kind of thought so. In order for it to be more in line with the grey/yellow icon in the urlbar. 
Did context menu icons even exist for back/forward/reload in 24-52? I know 29+ had black icons for those items, but only because Australis didn't display the context menu text for those items without CTR. 

I have an idea. While 24 didn't have icons in the context menu for those items, there were icons displayed if you were to right click on the back/forward buttons from the top navbar. Here's how it looks in Pale Moon 28, which has borrowed its UI from v24: 
![pmmmmmmm](https://user-images.githubusercontent.com/68521531/90711310-6232d580-e26e-11ea-9667-ca08eb7f28bd.png)

As for a contextual menu reload icon, I think one would have to be drawn up from scratch. Or rather leave the current one :) 

And finally, one last small thing that I have noticed. Web developer icons with Ff overrides enabled. A few look mismatched: 
![devel](https://user-images.githubusercontent.com/68521531/90711448-c2c21280-e26e-11ea-9015-4e79807cce75.png)

**Comment by B00ze64** [comment]
Good day.

I did not actually re-install FF24 to see which icons it used, though I could. I just searched for all PNG files in the Omni.ja archives and used whatever I found, where I thought it made sense (based on filename when possible). That's how I found the blue broom that I use for Erase-History - I have no idea where it was used in FF24, but it was in the package. If you want I can make the broom greyscale (it might match the clock a bit more)...

For Back/Forward I can search for those blue arrows, sure.

For the DevTools, they are all from FF24 but of course it did not have exactly the same tools, so some tools are not overridden and show whatever theme is selected prior. As for which icons are which tool, I based that on the filename; hopefully the name matched the tool, otherwise I may have mismatched some tools. The Remote Debugging is remote.png turned greyscale, the filename makes sense but I do not know if that's where the icon was used in the real FF24. The other two, FF24 did not have an eyedrop icon, and I have no idea what it used for Page Source.

Both Firefox and FirefoxSVG are wide-open to suggestions, as I do not have a live FF24 to play with and the SVG icons, well people can prefer other icons (none of them are official, I just re-use what's been used elsewhere in FF70+.)

Regards,

**Comment by B00ze64** [comment]
Hi @docrR.

I've pushed changes to the project (but did not create a release):

	- Opacity for inactive Clear Recent History (private window)
	- Opacity for inactive New Container Tab in File Menu (private window)
	- Bookmark-This was changed to use bookmark-1.png in Classic Firefox (white star)
	- Back/Forward/Stop/Reload/Bookmark in context menu now have Classic Firefox equivalents
	- Added some icons to the Classic Firefox: Checkmarks and Customize/Theme

You'll need the FuguePlus CSS (for the fixes to inactive icons) and the Menu and Library CSS for the classic Firefox theme. The new images you also need are:

        chrome/MipImages/FF/alerticon-info-positive(16x16).png
        chrome/MipImages/FF/menu-back.png
        chrome/MipImages/FF/menu-forward.png
        chrome/MipImages/FF/reload-stop-go-Reload(16x16).png
        chrome/MipImages/FF/reload-stop-go-Stop(16x16).png

Regards,
